services:
  postgres:
    image: postgres:18.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: backend-service
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d backend-service"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - nhp_network

  redis:
    image: redis:8.6
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s 
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - nhp_network

  backend-service:
    image: nhpdev2310/backend-service:${IMAGE_TAG}
    container_name: backend-service
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nhp_network

volumes:
  postgres_data:
  redis_data:
networks:
  nhp_network:
    driver: bridge