server:
  port: 8080

spring:
  config:
    import: optional:file:.env.dev[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  output:
    ansi:
      enabled: always

jwt:
  access_token:
    secret: ${ACCESS_KEY}
    expiration: 1
  refresh_token:
    secret: ${REFRESH_KEY}
    expiration: 14
  issuer: http://localhost:8080
  audience: backend-service

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE