package com.nhpdev.backendservicesecond.configuration;

import com.nhpdev.backendservicesecond.common.PermissionCode;
import com.nhpdev.backendservicesecond.common.nhpenum.UserStatus;
import com.nhpdev.backendservicesecond.entity.Permission;
import com.nhpdev.backendservicesecond.entity.Role;
import com.nhpdev.backendservicesecond.entity.User;
import com.nhpdev.backendservicesecond.repository.PermissionRepository;
import com.nhpdev.backendservicesecond.repository.RoleRepository;
import com.nhpdev.backendservicesecond.repository.UserRepository;
import jakarta.persistence.EntityManager;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.lang.reflect.Modifier;
import java.util.*;
import java.util.stream.Collectors;


@Component
@RequiredArgsConstructor
@Profile("dev")
@Slf4j
public class DataInitializer implements ApplicationRunner {

    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final PermissionRepository permissionRepository;
    private final PasswordEncoder passwordEncoder;
    private final InitDataProperties initDataProperties;
    private final EntityManager entityManager;

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void run(ApplicationArguments args) throws Exception {
        // 1. Khởi tạo & Cập nhật Quyền (Permissions)
        log.info("Bắt đầu tiến trình khởi tạo dữ liệu...");
        // BÓC TÁCH SESSION FACTORY TỪ ENTITY MANAGER RA Ở ĐÂY
        org.hibernate.Session session = entityManager.unwrap(org.hibernate.Session.class);
        org.hibernate.SessionFactory sessionFactory = session.getSessionFactory();
        // Làm sạch bộ đếm cũ
        sessionFactory.getStatistics().clear();
        sessionFactory.getStatistics().setStatisticsEnabled(true);
        Map<String, Permission> permissionMap = syncPermissions();
        Map<String, Role> roleMap = syncRoles(permissionMap);
        syncUser(roleMap);
        log.info("Hoàn tất khởi tạo dữ liệu thành công!");
        log.info(">>> STATISTIC:");
        log.info("\n{}", sessionFactory.getStatistics());
    }

    //============== PERMISSION SCAN===============
    private Map<String, Permission> syncPermissions() {
        // 1. Dùng Reflection quét các biến trong PermissionCode
        List<String> codePermissions = Arrays.stream(PermissionCode.class.getDeclaredFields())
                .filter(field ->
                        Modifier.isStatic(field.getModifiers())
                        && Modifier.isFinal(field.getModifiers())
                        && field.getType().equals(String.class)
                ).map(field -> {
                    try {
                        return (String) field.get(null);
                    } catch (IllegalAccessException e) {
                        throw new RuntimeException(e);
                    }
                })
                .filter(Objects::nonNull)
                .toList();
        // 2. Lấy dữ liệu từ DB
        List<Permission> existingPermissions = permissionRepository.findAll();
        Set<String> existingNames = existingPermissions.stream()
                .map(Permission::getName)
                .collect(Collectors.toSet());
        // 3. Lọc và chèn quyền mới
        List<Permission> newPermissions = codePermissions.stream()
                .filter(name -> !existingNames.contains(name))
                .map(name -> Permission.builder()
                        .name(name)
                        .description("Autogenerated permission:" + name)
                        .build())
                .toList();
        if(!newPermissions.isEmpty()) {
            permissionRepository.saveAll(newPermissions);
            log.info("Đã tự động gom {} permissions mới vào hàng đợi Batch", newPermissions.size());
            existingPermissions = new ArrayList<>(existingPermissions);
            existingPermissions.addAll(newPermissions);
        }
        return existingPermissions.stream()
                .collect(Collectors.toMap(Permission::getName, p -> p));
    }
    //============== ROLE INTEGRATION ===============
    private Map<String, Role> syncRoles(Map<String, Permission> permissionMap) {
        List<Role> existingRoles = roleRepository.findAll();
        Map<String, Role> roleMap = existingRoles.stream()
                .collect(Collectors.toMap(Role::getName, r -> r));
        List<Role> rolesToSave = new ArrayList<>();
        initDataProperties.getRoles().forEach(roleConfig -> {
            // Lấy Role cũ ra cập nhật, hoặc tạo mới nếu chưa có
            Role role = roleMap.getOrDefault(roleConfig.getName(),
                    Role.builder()
                            .name(roleConfig.getName())
                            .description(roleConfig.getDescription())
                            .build());

            // Ánh xạ danh sách String từ YAML sang Set<Permission>
            Set<Permission> mappedPermissions = new HashSet<>();
            if (roleConfig.getPermissions() != null) {
                mappedPermissions = roleConfig.getPermissions().stream()
                        .map(permissionMap::get)
                        .filter(Objects::nonNull)
                        .collect(Collectors.toSet());
            }

            // Gọi hàm xử lý thông minh nằm trong Entity
            role.syncPermissions(mappedPermissions);
            rolesToSave.add(role);
            roleMap.put(role.getName(), role);
        });
        if (!rolesToSave.isEmpty()) {
            roleRepository.saveAll(rolesToSave);
        }
        log.info("Đã hoàn thành đồng bộ {} roles hệ thống.", roleMap.size());
        return roleMap;
    }
    // ==================== INIT ACCOUNTS ====================
    public void syncUser(Map<String, Role> roleMap) {
        createUserDefault(
                initDataProperties.getSuperAdmin(),
                roleMap.get("SUPER_ADMIN")
        );
        createUserDefault(
                initDataProperties.getAdmin(),
                roleMap.get("ADMIN")
        );
    }

    private void createUserDefault(InitDataProperties.UserProperties userProps, Role role) {
        if (userProps == null || role == null) return;
        if(!userRepository.existsUsersByEmail(userProps.getEmail())) {
            User user = User.builder()
                    .email(userProps.getEmail())
                    .displayName(userProps.getDisplayName())
                    .password(passwordEncoder.encode(userProps.getPassword()))
                    .status(UserStatus.ACTIVE)
                    .build();
            user.addRole(role);
            userRepository.save(user);
            log.info("{} created successfully.", userProps.getEmail());
        }
    }
}
